name: 'GitOps Update'
description: 'Updates a key in a gitops repository and commit it'
inputs:
  filename: 
    description: 'Filename to update'
    required: true
  key-value:
    description: "The key to update. Usually it's yaml key like `this-is-key: value , new-key: value`"
    required: true
  github-deploy-key:  
    description: "Github deploy ssh private key to clone and commit target repository"
    required: true
  github-repo:
    description: "Target repository"
    required: true
  github-org:
    description: "Target organization"
    required: true
  username:
    description: "The username of the github user"
    required: true
  email:
    description: "The email of the github user"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@master
    - name: Golang
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.8'
      env:
        GO111MODULE: on
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: simplycubed/gitops-update
    - run: go run main.go ${{ inputs.key-value }} ${{ inputs.filename }} ${{ inputs.github-repo }} ${{ inputs.github-org }}
      shell: bash
      env:
        GITHUB_DEPLOY_KEY: ${{ inputs.github-deploy-key }}
        GITHUB_USERNAME: ${{ inputs.username }}
        EMAIL: ${{ inputs.email }}
